name: Build Lean documentation

on:
  push:
    branches:
      - master
    paths:
      - "**/*.lean"
      - "lakefile.lean"
      - "lakefile.toml"
      - "lean-toolchain"
      - "lake-manifest.json"
      - "references.bib"
      - ".github/workflows/docgen.yml"

  workflow_dispatch:

concurrency:
  group: docgen-master
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docgen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build and test Lean project
        uses: leanprover/lean-action@v1

      - name: Build and deploy Lean API documentation
        uses: leanprover-community/docgen-action@v1
        with:
          build-page: false
